// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntympepzlkvcuwpgtsxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50eW1wZXB6bGt2Y3V3cGd0c3h0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjI0MzksImV4cCI6MjA2OTc5ODQzOX0.8u3ul6nq7yvc6AMN-1EI_JevNasD40fu1ecP4Kd3g44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});